name: Job Dependencies Workflow

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Build
        run: echo "Building application..."
      - name: Simulate Build Process
        run: sleep 5

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Start Testing
        run: echo "Running tests..."
      - name: Simulate Test Process
        run: sleep 5

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Start Deploy
        run: echo "Deploying application..."
      - name: Simulate Deployment
        run: sleep 5